# Site settings
title: Benshkies Blog
email: blog@benshkies.dev
description: >-
  A blog based on CTF's, Digital Forensics, Cybersecurity
baseurl: ""
url: ""

# No remote theme — fully custom layouts and CSS
plugins:
  - jekyll-tagging
  - jekyll-feed
  - jekyll-seo-tag

# Tagging
tag_page_dir: tags
tag_page_layout: tag_page


# Pagination (if you add jekyll-paginate later)
# paginate: 6
# paginate_path: "/blog/page:num/"

# Author info (used in layouts)
author:
  name: Koy
  role: Digital Forensics & Cybersecurity
  bio: "I work in cybersecurity and love to do digital forensics challenges. Check out some of my posts for ones that I have solved in the past."
  github: benni371
  linkedin: koy-bennion  # add your linkedin username

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
